### ISSUE TITLE
Error	C4996	'j0': The POSIX name for this item is deprecated

### ISSUE THREAD

**Issue by KeithT** [tbennun/ceres-windows#10] opened 2017-05-31 10:20 UTC
Trying to get a x64 build working in vs2015 and after downloading ceres-windows and the latest stable ceres I get this error in the 21 places that reference jet.h.

Error	C4996	'j0': The POSIX name for this item is deprecated. Instead, use the ISO C and C++ conformant name: _j0. See online help for details.	helloworld_numeric_diff	c:\ceres_windows\ceres-windows-master\ceres-solver\include\ceres\jet.h	523	

_MSC_VER is defined as 1900 according to intellisense.

Are mods to ceres needed to get around this?

Thanks in advance for any suggestions.

**Comment by tbennun** [comment] 2017-05-31 11:30
This error occurs when the configuration file (config.h) is not included properly, since `CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS` is defined there.

Are you sure you are using the solution file and project files from this repository?

**Comment by KeithT** [comment] 2017-05-31 11:42
Yes definitely, I redownloaded everything and started from scratch a second time to be sure.
See attached screenshot of the project.
![ceres-windows-error1](https://cloud.githubusercontent.com/assets/1142989/26630446/fafa0c5a-4606-11e7-8bc8-b7f9a8c33798.jpg)

**Comment by KeithT** [comment] 2017-05-31 13:52
Tried it on another machine, just to ensure no legacy config issue on the first one and have the same errors.

**Comment by tbennun** [comment] 2017-05-31 14:23
I cannot reproduce that on a local machine I tested on.

Try manually defining it in the project properties (C/C++ -> Preprocessor -> Preprocessor Definitions)

Otherwise, try defining `_CRT_NONSTDC_NO_DEPRECATE`

**Comment by KeithT** [comment] 2017-05-31 14:56
Looking at this more closely it's only the samples which have the issue even though ceres_windows\ceres-windows-master\win\include\ceres\internal\config.h is in their external dependencies. 

Should this work out of the box or are there environment variables that need setting up?

**Comment by KeithT** [comment] 2017-05-31 15:53
No luck with the preprocessor suggestions. Thanks for the help though.

**Comment by tbennun** [comment] 2017-06-02 07:52
At this point, there is nothing further I can suggest. Just delete those lines and use the library normally.

Since I saw that you posted the same issue with the CMake version as well, I'm closing this issue for now.

If there is some solution that only relates to the project files (and not ceres-solver itself), please let me know and I'll fix it. Thanks for reporting!

**Closed as completed by tbennun** 2017-06-02 07:52 UTC
