### ISSUE TITLE
Compilation issues with VS2015

### ISSUE THREAD

**Issue by yuvalg1987** [tbennun/ceres-windows#14] opened 2017-12-20 08:26 UTC
Hi, 
I'm trying to compile with VS2015 but having some trouble. I managed to compile libglog_static and ceres_static without any issues but having some trouble compiling ceres due to linkage issues. In addition it seems that the examples are based on the ceres compilation and therefor cannot be compiled.  I'm getting the following error:
>libglog_static.lib(utilities.obj) : error LNK2019: unresolved external symbol "bool __cdecl google::glog_internal_namespace_::IsFailureSignalHandlerInstalled(void)" (?IsFailureSignalHandlerInstalled@glog_internal_namespace_@google@@YA_NXZ) referenced in function "void __cdecl google::DumpStackTraceAndExit(void)" (?DumpStackTraceAndExit@google@@YAXXZ)

1>libglog_static.lib(utilities.obj) : error LNK2019: unresolved external symbol "bool __cdecl google::Symbolize(void *,char *,int)" (?Symbolize@google@@YA_NPEAXPEADH@Z) referenced in function "void __cdecl google::DumpPCAndSymbol(void (__cdecl*)(char const *,void *),void *,void *,char const * const)" (?DumpPCAndSymbol@google@@YAXP6AXPEBDPEAX@Z11QEBD@Z)

1>C:\ceres-solver\x64\Debug\ceres.dll : fatal error LNK1120: 2 unresolved externals

Any advice?

**Comment by NeoPhix** [comment] 2017-12-20 09:07
I have the same problem with linking a .dll. When I try a stupid solution - to write my own simple realization ({ return false ;} after function declaration) the linker tells me that IsFailureSignalHandlerInstalled exists in blas.obj binary file, but it is no definition of this function in blas.cc file. Any another idea? May be the problem is in linking order?

**Comment by tbennun** [comment] 2017-12-20 09:12
Thanks for reporting, I'll look into it.

Are you both using the version of the submodules from this git repo? If not, which version of ceres-solver are you using?

**Comment by yuvalg1987** [comment] 2017-12-20 09:14
Yes. I've downloaded  ceres-solver-1.12.0 as required.

**Comment by NeoPhix** [comment] 2017-12-20 09:37
+1

**Comment by NeoPhix** [comment] 2017-12-20 10:15
I have won it (compiling the dll): need to add demangle.cc, symbolyze.cc and signalhandler.cc into glog sources in VS project. 
But now I have another problem with deprecated POSIX names (j0 instead _j0) when compiling samples. I'm trying to fix it! :) 
![image](https://user-images.githubusercontent.com/8876827/34202084-c8a0ea50-e587-11e7-9b3a-a578f7ddc7b9.png)

**Comment by yuvalg1987** [comment] 2017-12-20 10:18
This I managed to solve. Simply change j0,j1,jN to _j0, j1, jN in the mentioned files.

**Comment by yuvalg1987** [comment] 2017-12-20 10:19
Where did you get these files from (  demangle.cc, symbolyze.cc and signalhandler.cc) ?

**Comment by NeoPhix** [comment] 2017-12-20 10:20
files lie at glog/src

about j0 to _j0 - the problem is no definition of _j0 etc funcs. Now I am searching where to define it :)

**Comment by NeoPhix** [comment] 2017-12-20 11:08
I found only one solution - delete `&& defined(_j0)` from jet.h. Don't know why my preprocessor don't understand defined in math.h methods. I have checked that <cmath> is included.

**Comment by tbennun** [comment] 2017-12-20 15:08
@NeoPhix @yuvalg1987 Does this mean that with PR #15 the DLL compiles successfully?

About _j0 vs. j0: I remember having this exact discussion with the ceres-solver team, and they had a good reason to keep it as a configuration definition (see [config.h:100](../blob/master/win/include/ceres/internal/config.h#L100)). It's just that something is including `jet.h` without first including `config.h` (where `CERES_MSVC_USE_UNDERSCORE_PREFIXED_BESSEL_FUNCTIONS` is defined)

**Comment by tbennun** [comment] 2017-12-20 15:09
If you want, you can add that definition to your project properties manually.

**Comment by NeoPhix** [comment] 2017-12-20 15:16
Yes, this PR fixes dll linking. 

Thank you for advice about j0 vs _j0. Now all samples compiles successfully too.

**Comment by tbennun** [comment] 2017-12-20 15:17
@yuvalg1987 once you confirm that everything works for you, I'll close the issue.

**Comment by yuvalg1987** [comment] 2017-12-20 17:32
Hi, Everything compiles Ok although I'm having some performance issues. I running the same code with ceres-solver on Ubuntu and Windows and having huge difference in the computation time (Hardware is relatively the same), Is it because ceres-solver for windows has less features?

**Closed as completed** 2019-01-11 15:42 UTC
